// InstallInfo.cs - Models for InstallInfo.yaml (Munki-style catalog cache)
// Contains information about optional installs, managed installs, updates, and problem items

using Microsoft.UI.Xaml.Media.Imaging;
using YamlDotNet.Serialization;

namespace Cimian.GUI.ManagedSoftwareCenter.Models;

/// <summary>
/// Represents the InstallInfo.yaml structure (like Munki's InstallInfo.plist)
/// Generated by managedsoftwareupdate during check phase
/// </summary>
public class InstallInfo
{
    /// <summary>
    /// Items available for optional installation by users
    /// </summary>
    [YamlMember(Alias = "optional_installs")]
    public List<InstallableItem> OptionalInstalls { get; set; } = [];

    /// <summary>
    /// Items scheduled for installation (admin-managed + user selections)
    /// </summary>
    [YamlMember(Alias = "managed_installs")]
    public List<InstallableItem> ManagedInstalls { get; set; } = [];

    /// <summary>
    /// Items scheduled for removal
    /// </summary>
    [YamlMember(Alias = "removals")]
    public List<InstallableItem> Removals { get; set; } = [];

    /// <summary>
    /// Updates available for installed managed software
    /// </summary>
    [YamlMember(Alias = "managed_updates")]
    public List<InstallableItem> ManagedUpdates { get; set; } = [];

    /// <summary>
    /// Featured/highlighted optional items
    /// </summary>
    [YamlMember(Alias = "featured_items")]
    public List<string> FeaturedItems { get; set; } = [];

    /// <summary>
    /// Items that encountered installation problems
    /// </summary>
    [YamlMember(Alias = "problem_items")]
    public List<ProblemItem> ProblemItems { get; set; } = [];

    /// <summary>
    /// Timestamp when this info was generated
    /// </summary>
    [YamlMember(Alias = "last_check")]
    public DateTime LastCheck { get; set; }
}

/// <summary>
/// Represents a software item that can be installed/updated/removed
/// </summary>
public class InstallableItem
{
    /// <summary>
    /// Internal name/identifier
    /// </summary>
    [YamlMember(Alias = "name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// User-friendly display name
    /// </summary>
    [YamlMember(Alias = "display_name")]
    public string? DisplayName { get; set; }

    /// <summary>
    /// Version to be installed
    /// </summary>
    [YamlMember(Alias = "version")]
    public string Version { get; set; } = string.Empty;

    /// <summary>
    /// Currently installed version (if any)
    /// </summary>
    [YamlMember(Alias = "installed_version")]
    public string? InstalledVersion { get; set; }

    /// <summary>
    /// Description of the software
    /// </summary>
    [YamlMember(Alias = "description")]
    public string? Description { get; set; }

    /// <summary>
    /// Category for grouping
    /// </summary>
    [YamlMember(Alias = "category")]
    public string? Category { get; set; }

    /// <summary>
    /// Developer/publisher name
    /// </summary>
    [YamlMember(Alias = "developer")]
    public string? Developer { get; set; }

    /// <summary>
    /// URL to icon image
    /// </summary>
    [YamlMember(Alias = "icon")]
    public string? Icon { get; set; }

    /// <summary>
    /// Size of the installer in bytes
    /// </summary>
    [YamlMember(Alias = "installer_item_size")]
    public long InstallerItemSize { get; set; }

    /// <summary>
    /// Size of installed software in bytes
    /// </summary>
    [YamlMember(Alias = "installed_size")]
    public long InstalledSize { get; set; }

    /// <summary>
    /// Whether the item is already installed
    /// </summary>
    [YamlMember(Alias = "installed")]
    public bool Installed { get; set; }

    /// <summary>
    /// Whether uninstall is supported
    /// </summary>
    [YamlMember(Alias = "uninstallable")]
    public bool Uninstallable { get; set; }

    /// <summary>
    /// Current status of the item
    /// </summary>
    [YamlMember(Alias = "status")]
    public string? Status { get; set; }

    /// <summary>
    /// Whether item requires restart after install
    /// </summary>
    [YamlMember(Alias = "restart_action")]
    public string? RestartAction { get; set; }

    /// <summary>
    /// Whether user requested this install
    /// </summary>
    [YamlMember(Alias = "user_requested")]
    public bool UserRequested { get; set; }

    /// <summary>
    /// Whether item will be installed in this session
    /// </summary>
    [YamlMember(Alias = "will_be_installed")]
    public bool WillBeInstalled { get; set; }

    /// <summary>
    /// Whether item will be removed in this session
    /// </summary>
    [YamlMember(Alias = "will_be_removed")]
    public bool WillBeRemoved { get; set; }

    /// <summary>
    /// Path to installer item (if downloaded)
    /// </summary>
    [YamlMember(Alias = "installer_item")]
    public string? InstallerItem { get; set; }

    /// <summary>
    /// Additional notes about the item
    /// </summary>
    [YamlMember(Alias = "notes")]
    public string? Notes { get; set; }

    /// <summary>
    /// Release notes for this version
    /// </summary>
    [YamlMember(Alias = "release_notes")]
    public string? ReleaseNotes { get; set; }

    /// <summary>
    /// URLs to screenshot images
    /// </summary>
    [YamlMember(Alias = "screenshots")]
    public List<string>? Screenshots { get; set; }

    /// <summary>
    /// Alert to display before installing
    /// </summary>
    [YamlMember(Alias = "preinstall_alert")]
    public AlertInfo? PreinstallAlert { get; set; }

    /// <summary>
    /// Alert to display before uninstalling
    /// </summary>
    [YamlMember(Alias = "preuninstall_alert")]
    public AlertInfo? PreuninstallAlert { get; set; }

    /// <summary>
    /// Alert to display before upgrading
    /// </summary>
    [YamlMember(Alias = "preupgrade_alert")]
    public AlertInfo? PreupgradeAlert { get; set; }

    /// <summary>
    /// Date after which this item must be force-installed
    /// </summary>
    [YamlMember(Alias = "force_install_after_date")]
    public DateTime? ForceInstallAfterDate { get; set; }

    /// <summary>
    /// List of item names that depend on this item
    /// </summary>
    [YamlMember(Alias = "dependent_items")]
    public List<string>? DependentItems { get; set; }

    /// <summary>
    /// Applications that must be quit before installing
    /// </summary>
    [YamlMember(Alias = "blocking_applications")]
    public List<string>? BlockingApplications { get; set; }

    /// <summary>
    /// Reason why the item is unavailable (license, OS version, disk space, etc.)
    /// </summary>
    [YamlMember(Alias = "note")]
    public string? Note { get; set; }

    /// <summary>
    /// Whether restart is required after installation
    /// </summary>
    public bool RestartRequired => !string.IsNullOrEmpty(RestartAction) && 
        RestartAction.Equals("RequireRestart", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Gets the effective display name
    /// </summary>
    public string GetDisplayName() => DisplayName ?? Name;

    /// <summary>
    /// Gets user-friendly status text for display
    /// </summary>
    public string StatusText => Status switch
    {
        ItemStatus.Installed => "Installed",
        ItemStatus.NotInstalled => "",
        ItemStatus.InstallRequested => "Install pending",
        ItemStatus.WillBeInstalled => "Will be installed",
        ItemStatus.UpdateAvailable => "Update available",
        ItemStatus.UpdateWillBeInstalled => "Update pending",
        ItemStatus.RemovalRequested => "Removal pending",
        ItemStatus.WillBeRemoved => "Will be removed",
        ItemStatus.Downloading => "Downloading...",
        ItemStatus.Installing => "Installing...",
        ItemStatus.InstallError => "Install failed",
        ItemStatus.RemovalError => "Removal failed",
        ItemStatus.Unavailable => "Unavailable",
        ItemStatus.InstalledNotRemovable => "Installed",
        ItemStatus.MustBeInstalled => "Required",
        _ => Installed ? "Installed" : ""
    };

    /// <summary>
    /// Cached icon image for UI binding (not serialized)
    /// </summary>
    [YamlIgnore]
    public BitmapImage? IconImage { get; set; }

    /// <summary>
    /// Days pending text for UI binding (not serialized)
    /// </summary>
    [YamlIgnore]
    public string? DaysPendingText { get; set; }

    /// <summary>
    /// Whether days pending text should be shown
    /// </summary>
    [YamlIgnore]
    public bool HasDaysPendingText => !string.IsNullOrEmpty(DaysPendingText);

    /// <summary>
    /// Whether this item has a force install deadline
    /// </summary>
    [YamlIgnore]
    public bool HasDeadline => ForceInstallAfterDate.HasValue;

    /// <summary>
    /// Warning text for force_install_after_date
    /// </summary>
    [YamlIgnore]
    public string? DeadlineText
    {
        get
        {
            if (!ForceInstallAfterDate.HasValue) return null;
            var remaining = ForceInstallAfterDate.Value - DateTime.Now;
            if (remaining.TotalDays < 0)
                return "This item is past its installation deadline!";
            if (remaining.TotalHours < 1)
                return "This item must be installed within the hour!";
            if (remaining.TotalDays < 1)
                return $"This item must be installed within {(int)remaining.TotalHours} hours";
            return $"This item must be installed by {ForceInstallAfterDate.Value:g}";
        }
    }

    /// <summary>
    /// Size in bytes for binding
    /// </summary>
    public long InstallerSize => InstallerItemSize > 0 ? InstallerItemSize : InstalledSize;

    /// <summary>
    /// Gets formatted size string
    /// </summary>
    public string GetFormattedSize()
    {
        var size = InstallerItemSize > 0 ? InstallerItemSize : InstalledSize;
        return size switch
        {
            < 1024 => $"{size} B",
            < 1024 * 1024 => $"{size / 1024.0:F1} KB",
            < 1024 * 1024 * 1024 => $"{size / (1024.0 * 1024.0):F1} MB",
            _ => $"{size / (1024.0 * 1024.0 * 1024.0):F2} GB"
        };
    }
}

/// <summary>
/// Represents an item that had installation problems
/// </summary>
public class ProblemItem
{
    [YamlMember(Alias = "name")]
    public string Name { get; set; } = string.Empty;

    [YamlMember(Alias = "display_name")]
    public string? DisplayName { get; set; }

    [YamlMember(Alias = "version")]
    public string? Version { get; set; }

    [YamlMember(Alias = "error_message")]
    public string? ErrorMessage { get; set; }

    [YamlMember(Alias = "note")]
    public string? Note { get; set; }

    public string GetDisplayName() => DisplayName ?? Name;
}

/// <summary>
/// Alert information for pre-install/uninstall/upgrade dialogs
/// </summary>
public class AlertInfo
{
    [YamlMember(Alias = "alert_title")]
    public string? AlertTitle { get; set; }

    [YamlMember(Alias = "alert_detail")]
    public string? AlertDetail { get; set; }

    [YamlMember(Alias = "ok_label")]
    public string? OkLabel { get; set; }

    [YamlMember(Alias = "cancel_label")]
    public string? CancelLabel { get; set; }
}

/// <summary>
/// Possible status values for installable items
/// </summary>
public static class ItemStatus
{
    public const string NotInstalled = "not-installed";
    public const string Installed = "installed";
    public const string InstallRequested = "install-requested";
    public const string WillBeInstalled = "will-be-installed";
    public const string UpdateAvailable = "update-available";
    public const string UpdateWillBeInstalled = "update-will-be-installed";
    public const string RemovalRequested = "removal-requested";
    public const string WillBeRemoved = "will-be-removed";
    public const string Downloading = "downloading";
    public const string Installing = "installing";
    public const string InstallError = "install-error";
    public const string RemovalError = "removal-error";
    public const string Unavailable = "unavailable";
    public const string InstalledNotRemovable = "installed-not-removable";
    public const string MustBeInstalled = "must-be-installed";
}
