// HistoryViewModel.cs - ViewModel for Installation History page

using System.Collections.ObjectModel;
using System.Text.Json;
using CommunityToolkit.Mvvm.ComponentModel;
using Cimian.Core.Services;

namespace Cimian.GUI.ManagedSoftwareCenter.ViewModels;

/// <summary>
/// ViewModel for the History page - shows past installation sessions
/// Reads from sessions.json generated by SessionLogger
/// </summary>
public partial class HistoryViewModel : ObservableObject
{
    private static readonly string SessionsPath =
        Path.Combine(@"C:\ProgramData\ManagedInstalls\reports", "sessions.json");

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        PropertyNameCaseInsensitive = true
    };

    [ObservableProperty]
    public partial ObservableCollection<HistoryEntry> Sessions { get; set; } = [];

    [ObservableProperty]
    public partial bool IsLoading { get; set; }

    [ObservableProperty]
    public partial bool IsEmpty { get; set; }

    public async Task LoadAsync()
    {
        IsLoading = true;
        try
        {
            var entries = new List<HistoryEntry>();

            if (File.Exists(SessionsPath))
            {
                List<SessionData>? sessions = null;
                try
                {
                    var json = await File.ReadAllTextAsync(SessionsPath);
                    sessions = JsonSerializer.Deserialize<List<SessionData>>(json, JsonOptions);
                }
                catch { }

                if (sessions != null)
                {
                    foreach (var session in sessions)
                    {
                        if (!DateTime.TryParse(session.StartTime, out var startTime))
                            continue;

                        entries.Add(new HistoryEntry
                        {
                            SessionId = session.SessionId,
                            StartTime = startTime,
                            RunType = session.RunType ?? "unknown",
                            Status = session.Status ?? "unknown",
                            DurationSeconds = session.DurationSeconds ?? 0,
                            Installs = session.Summary?.Installs ?? 0,
                            Updates = session.Summary?.Updates ?? 0,
                            Removals = session.Summary?.Removals ?? 0,
                            Successes = session.Summary?.Successes ?? 0,
                            Failures = session.Summary?.Failures ?? 0,
                            PackagesHandled = session.Summary?.PackagesHandled ?? []
                        });
                    }
                }
            }

            Sessions = new ObservableCollection<HistoryEntry>(
                entries.OrderByDescending(e => e.StartTime));
            IsEmpty = Sessions.Count == 0;
        }
        finally
        {
            IsLoading = false;
        }
    }
}

/// <summary>
/// A single history entry representing one update session
/// </summary>
public class HistoryEntry
{
    public string SessionId { get; set; } = "";
    public DateTime StartTime { get; set; }
    public string RunType { get; set; } = "";
    public string Status { get; set; } = "";
    public long DurationSeconds { get; set; }
    public int Installs { get; set; }
    public int Updates { get; set; }
    public int Removals { get; set; }
    public int Successes { get; set; }
    public int Failures { get; set; }
    public List<string> PackagesHandled { get; set; } = [];

    public string DateText => StartTime.ToString("MMM d, yyyy  h:mm tt");

    public string SummaryText
    {
        get
        {
            var parts = new List<string>();
            if (Installs > 0) parts.Add($"{Installs} install{(Installs != 1 ? "s" : "")}");
            if (Updates > 0) parts.Add($"{Updates} update{(Updates != 1 ? "s" : "")}");
            if (Removals > 0) parts.Add($"{Removals} removal{(Removals != 1 ? "s" : "")}");
            return parts.Count > 0 ? string.Join(", ", parts) : "No actions";
        }
    }

    public string DurationText
    {
        get
        {
            if (DurationSeconds < 60) return $"{DurationSeconds}s";
            var mins = DurationSeconds / 60;
            var secs = DurationSeconds % 60;
            return secs > 0 ? $"{mins}m {secs}s" : $"{mins}m";
        }
    }

    public string StatusIcon => Status switch
    {
        "completed" => "\uE73E",  // Checkmark
        "failed" => "\uE711",     // Cancel
        "partial_failure" => "\uE7BA",  // Warning
        _ => "\uE946"             // Info
    };

    public string RunTypeBadge => RunType switch
    {
        "auto" => "Auto",
        "bootstrap" => "Bootstrap",
        "manual" => "Manual",
        "checkonly" => "Check Only",
        "installonly" => "Install Only",
        _ => RunType
    };

    public bool HasFailures => Failures > 0;
    public string PackageList => string.Join(", ", PackagesHandled);
}
