name: Go Test

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    timeout-minutes: 25

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Build all binaries
      run: |
        for /D %%D in (cmd/*) do (
          cd %%D
          go build -v
        )

    - name: Run Tests
      run: go test -race -cover ./...
