name: Go Test

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    timeout-minutes: 25

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Build Binaries
      shell: pwsh
      run: |
        $projects = Get-ChildItem -Directory -Path cmd/* -Recurse
        foreach ($project in $projects) {
          Write-Host "Building project: $($project.FullName)"
          cd $project.FullName
          mkdir bin -ErrorAction SilentlyContinue
          go build -o bin/
          cd ..
        }
    
    - name: Verify Output
      shell: pwsh
      run: |
        Write-Host "Verifying binaries in 'cmd/*/bin/' directories..."
        Get-ChildItem -Path cmd/*/bin/*.exe -Recurse | ForEach-Object { 
          Write-Host "Found binary: $($_.FullName)" 
        }
