name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        targetplatform: [x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NuGet
        run: |
          if (-not (Get-Command nuget.exe -ErrorAction SilentlyContinue)) {
            choco install nuget.commandline --no-progress --yes
          } else {
            Write-Host "NuGet is already installed."
          }

      - name: Install IntuneWinAppUtil
        run: |
          if (-not (Get-Command IntuneWinAppUtil.exe -ErrorAction SilentlyContinue)) {
            choco install intunewinapputil --no-progress --yes
          } else {
            Write-Host "IntuneWinAppUtil is already installed."
          }

      - name: Check for WiX Installation
        run: |
          if (-not (Test-Path "C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe")) {
            choco install wixtoolset --version=3.14 --no-progress --yes --force
          } else {
            Write-Host "WiX Toolset v3.14 is already installed."
          }

      - name: Set up Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0

      - name: Prepare Release Version
        id: set_version
        shell: pwsh
        run: |
          $version = Get-Date -Format "yyyy.MM.dd"
          echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Build All Binaries
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $projects = Get-ChildItem -Directory -Path cmd/* -Recurse
          foreach ($project in $projects) {
            cd $project.FullName
            $binaryName = $project.Name
            go build -v -o bin\$binaryName.exe -ldflags=@"
              -X github.com/rodchristiansen/gorilla/pkg/version.appName=$binaryName `
              -X github.com/rodchristiansen/gorilla/pkg/version.version=${{ env.RELEASE_VERSION }} `
              -X github.com/rodchristiansen/gorilla/pkg/version.branch=${{ github.ref_name }} `
              -X github.com/rodchristiansen/gorilla/pkg/version.buildDate=$(Get-Date -Format s) `
              -X github.com/rodchristiansen/gorilla/pkg/version.revision=$(git rev-parse HEAD)
            "@
          }          
          cd ${{ github.workspace }} # Reset to root after builds

      - name: Package Binaries
        shell: pwsh
        run: |
          mkdir -p release
          Get-ChildItem -Path cmd/*/bin/*.exe | ForEach-Object {
            Copy-Item $_.FullName release/
          }
          tar -czvf release.tar.gz -C release .

      - name: Build MSI Package with WiX
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          & "C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe" -ext WixUtilExtension.dll -o build/msi.wixobj build/msi.wxs
          & "C:\Program Files (x86)\WiX Toolset v3.14\bin\light.exe" -ext WixUtilExtension.dll -o release/gorilla.msi build/msi.wixobj

      - name: Prepare NuGet Package
        shell: pwsh
        run: |
          $version = $env:RELEASE_VERSION
          (Get-Content build/nupkg.nuspec) -replace '\$\{\{ env\.RELEASE_VERSION \}\}', $version | Set-Content build/nupkg.nuspec
          nuget pack build/nupkg.nuspec -OutputDirectory release -BasePath $PWD

      - name: Prepare IntuneWin Package
        shell: pwsh
        run: |
          pwsh build/intunewin.ps1 -SetupFolder release -SetupFile release/gorilla.nupkg -OutputFolder release/intunewin

      - name: Verify Generated Files
        shell: pwsh
        run: |
          if (-not (Get-ChildItem release)) {
            Write-Error "No files generated in release folder!"
            exit 1
          }
          Get-ChildItem release

      - name: Create GitHub Release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $releaseFiles = Get-ChildItem -Path release/* | ForEach-Object { $_.FullName -replace '\\', '/' }
          gh release create $env:RELEASE_VERSION $releaseFiles `
            --title "GorillaPkg v$env:RELEASE_VERSION" `
            --notes "Automated release for version $env:RELEASE_VERSION."
